### ISSUE TITLE
can you share exact notebook as presented in video

### ISSUE THREAD

**Issue by Sandy4321** [cuda-mode/lecture2#3]
great material thanks
but can you share exact notebook as presented in video
for example  presented at 13:19 is not in gihub notebook 
https://youtu.be/nOxKexn3iBo?t=798

![image](https://github.com/cuda-mode/lecture2/assets/11426119/eb34ec15-bafb-4e2a-9b45-8ffebfe29056)

**Comment by msaroufim** [comment]
The talk was re-recorded and I'd imagine Jeremy put in what he thought was the better version of the notebook so gonna close this for now

**Comment by Sandy4321** [comment]
OK
